// plonk the recipes JSON in the window object
window.recipes = JSON.stringify(
{
  "express-transport-belt":{
    "enabled":false,
    "name":"express-transport-belt",
    "result":"express-transport-belt",
    "category":"crafting-with-fluid",
    "type":"recipe",
    "requester_paste_multiplier":4,
    "ingredients":[["iron-gear-wheel",5],["fast-transport-belt",1],{
        "type":"fluid",
        "name":"lubricant",
        "amount":2
      }]
  },
  "rail-signal":{
    "enabled":false,
    "name":"rail-signal",
    "result":"rail-signal",
    "ingredients":[["electronic-circuit",1],["iron-plate",5]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "burner-mining-drill":{
    "name":"burner-mining-drill",
    "result":"burner-mining-drill",
    "ingredients":[["iron-gear-wheel",3],["stone-furnace",1],["iron-plate",3]],
    "type":"recipe",
    "energy_required":2
  },
  "flame-thrower":{
    "enabled":false,
    "name":"flame-thrower",
    "result":"flame-thrower",
    "ingredients":[["steel-plate",5],["iron-gear-wheel",10]],
    "type":"recipe",
    "energy_required":10
  },
  "steel-furnace":{
    "enabled":false,
    "name":"steel-furnace",
    "result":"steel-furnace",
    "ingredients":[["steel-plate",8],["stone-brick",10]],
    "type":"recipe",
    "energy_required":3
  },
  "productivity-module-2":{
    "enabled":false,
    "name":"productivity-module-2",
    "result":"productivity-module-2",
    "ingredients":[["productivity-module",4],["advanced-circuit",5],["processing-unit",5]],
    "type":"recipe",
    "energy_required":30
  },
  "slowdown-capsule":{
    "enabled":false,
    "name":"slowdown-capsule",
    "result":"slowdown-capsule",
    "ingredients":[["steel-plate",2],["electronic-circuit",2],["coal",5]],
    "type":"recipe",
    "energy_required":8
  },
  "underground-belt":{
    "enabled":false,
    "name":"underground-belt",
    "result_count":2,
    "ingredients":[["iron-plate",10],["transport-belt",5]],
    "result":"underground-belt",
    "type":"recipe",
    "requester_paste_multiplier":4,
    "energy_required":1
  },
  "battery-mk2-equipment":{
    "enabled":false,
    "name":"battery-mk2-equipment",
    "result":"battery-mk2-equipment",
    "ingredients":[["battery-equipment",10],["processing-unit",20]],
    "type":"recipe",
    "energy_required":10
  },
  "filter-inserter":{
    "enabled":false,
    "name":"filter-inserter",
    "result":"filter-inserter",
    "ingredients":[["fast-inserter",1],["electronic-circuit",4]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "pipe":{
    "name":"pipe",
    "result":"pipe",
    "ingredients":[["iron-plate",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "night-vision-equipment":{
    "enabled":false,
    "name":"night-vision-equipment",
    "result":"night-vision-equipment",
    "ingredients":[["advanced-circuit",5],["steel-plate",10]],
    "type":"recipe",
    "energy_required":10
  },
  "copper-cable":{
    "name":"copper-cable",
    "result":"copper-cable",
    "ingredients":[["copper-plate",1]],
    "type":"recipe",
    "requester_paste_multiplier":10,
    "result_count":2
  },
  "heavy-oil-cracking":{
    "name":"heavy-oil-cracking",
    "ingredients":[{
        "type":"fluid",
        "name":"water",
        "amount":3
      },{
        "type":"fluid",
        "name":"heavy-oil",
        "amount":4
      }],
    "subgroup":"fluid-recipes",
    "type":"recipe",
    "energy_required":5,
    "enabled":false,
    "results":[{
        "type":"fluid",
        "name":"light-oil",
        "amount":3
      }],
    "category":"chemistry",
    "main_product":"",
    "icon":"__base__/graphics/icons/fluid/heavy-oil-cracking.png",
    "order":"b[fluid-chemistry]-a[heavy-oil-cracking]"
  },
  "copper-plate":{
    "name":"copper-plate",
    "result":"copper-plate",
    "category":"smelting",
    "type":"recipe",
    "ingredients":[["copper-ore",1]],
    "energy_required":3.5
  },
  "fast-transport-belt":{
    "enabled":false,
    "name":"fast-transport-belt",
    "result":"fast-transport-belt",
    "ingredients":[["iron-gear-wheel",5],["transport-belt",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "distractor-capsule":{
    "enabled":false,
    "name":"distractor-capsule",
    "result":"distractor-capsule",
    "ingredients":[["defender-capsule",4],["advanced-circuit",3]],
    "type":"recipe",
    "energy_required":15
  },
  "fast-splitter":{
    "enabled":false,
    "name":"fast-splitter",
    "result":"fast-splitter",
    "ingredients":[["splitter",1],["iron-gear-wheel",10],["electronic-circuit",10]],
    "type":"recipe",
    "requester_paste_multiplier":4,
    "energy_required":2
  },
  "piercing-shotgun-shell":{
    "enabled":false,
    "name":"piercing-shotgun-shell",
    "result":"piercing-shotgun-shell",
    "ingredients":[["copper-plate",2],["steel-plate",2]],
    "type":"recipe",
    "energy_required":8
  },
  "pipe-to-ground":{
    "name":"pipe-to-ground",
    "result_count":2,
    "ingredients":[["pipe",10],["iron-plate",5]],
    "type":"recipe",
    "requester_paste_multiplier":4,
    "result":"pipe-to-ground"
  },
  "gate":{
    "enabled":false,
    "name":"gate",
    "result":"gate",
    "ingredients":[["stone-wall",1],["steel-plate",2],["electronic-circuit",2]],
    "type":"recipe"
  },
  "railgun-dart":{
    "enabled":false,
    "name":"railgun-dart",
    "result":"railgun-dart",
    "ingredients":[["steel-plate",5],["electronic-circuit",5]],
    "type":"recipe",
    "energy_required":8
  },
  "rail-chain-signal":{
    "enabled":false,
    "name":"rail-chain-signal",
    "result":"rail-chain-signal",
    "ingredients":[["electronic-circuit",1],["iron-plate",5]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "engine-unit":{
    "enabled":false,
    "name":"engine-unit",
    "result":"engine-unit",
    "category":"advanced-crafting",
    "type":"recipe",
    "ingredients":[["steel-plate",1],["iron-gear-wheel",1],["pipe",2]],
    "energy_required":20
  },
  "gun-turret":{
    "enabled":false,
    "name":"gun-turret",
    "result":"gun-turret",
    "ingredients":[["iron-gear-wheel",10],["copper-plate",10],["iron-plate",20]],
    "type":"recipe",
    "energy_required":10
  },
  "processing-unit":{
    "enabled":false,
    "name":"processing-unit",
    "result":"processing-unit",
    "category":"crafting-with-fluid",
    "type":"recipe",
    "ingredients":[["electronic-circuit",20],["advanced-circuit",2],{
        "type":"fluid",
        "name":"sulfuric-acid",
        "amount":0.5
      }],
    "energy_required":15
  },
  "cluster-grenade":{
    "enabled":false,
    "name":"cluster-grenade",
    "result":"cluster-grenade",
    "ingredients":[["grenade",7],["explosives",5],["steel-plate",5]],
    "type":"recipe",
    "energy_required":8
  },
  "iron-chest":{
    "enabled":true,
    "name":"iron-chest",
    "result":"iron-chest",
    "ingredients":[["iron-plate",8]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "grenade":{
    "enabled":false,
    "name":"grenade",
    "result":"grenade",
    "ingredients":[["iron-plate",5],["coal",10]],
    "type":"recipe",
    "energy_required":8
  },
  "rocket-launcher":{
    "enabled":false,
    "name":"rocket-launcher",
    "result":"rocket-launcher",
    "ingredients":[["iron-plate",5],["iron-gear-wheel",5],["electronic-circuit",5]],
    "type":"recipe",
    "energy_required":5
  },
  "explosive-cannon-shell":{
    "enabled":false,
    "name":"explosive-cannon-shell",
    "result":"explosive-cannon-shell",
    "ingredients":[["steel-plate",4],["plastic-bar",2],["explosives",4]],
    "type":"recipe",
    "energy_required":8
  },
  "steam-engine":{
    "name":"steam-engine",
    "type":"recipe",
    "result":"steam-engine",
    "ingredients":[["iron-gear-wheel",5],["pipe",5],["iron-plate",5]]
  },
  "beacon":{
    "enabled":false,
    "name":"beacon",
    "result":"beacon",
    "ingredients":[["electronic-circuit",20],["advanced-circuit",20],["steel-plate",10],["copper-cable",10]],
    "type":"recipe",
    "energy_required":15
  },
  "iron-axe":{
    "name":"iron-axe",
    "type":"recipe",
    "result":"iron-axe",
    "ingredients":[["iron-stick",2],["iron-plate",3]]
  },
  "solar-panel-equipment":{
    "enabled":false,
    "name":"solar-panel-equipment",
    "result":"solar-panel-equipment",
    "ingredients":[["solar-panel",5],["processing-unit",1],["steel-plate",5]],
    "type":"recipe",
    "energy_required":10
  },
  "steel-axe":{
    "enabled":false,
    "name":"steel-axe",
    "result":"steel-axe",
    "ingredients":[["steel-plate",5],["iron-stick",2]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "player-port":{
    "enabled":false,
    "name":"player-port",
    "result":"player-port",
    "ingredients":[["electronic-circuit",10],["iron-gear-wheel",5],["iron-plate",1]],
    "type":"recipe"
  },
  "power-armor-mk2":{
    "enabled":false,
    "name":"power-armor-mk2",
    "result":"power-armor-mk2",
    "ingredients":[["effectivity-module-3",5],["speed-module-3",5],["processing-unit",40],["steel-plate",40],["alien-artifact",50]],
    "type":"recipe",
    "requester_paste_multiplier":1,
    "energy_required":25
  },
  "science-pack-3":{
    "enabled":false,
    "name":"science-pack-3",
    "result":"science-pack-3",
    "ingredients":[["battery",1],["advanced-circuit",1],["filter-inserter",1],["steel-plate",1]],
    "type":"recipe",
    "energy_required":12
  },
  "empty-barrel":{
    "name":"empty-barrel",
    "ingredients":[{
        "type":"item",
        "name":"steel-plate",
        "amount":1
      }],
    "subgroup":"barrel",
    "type":"recipe",
    "requester_paste_multiplier":10,
    "energy_required":1,
    "enabled":false,
    "results":[{
        "type":"item",
        "name":"empty-barrel",
        "amount":1
      }],
    "category":"crafting"
  },
  "heavy-armor":{
    "enabled":false,
    "name":"heavy-armor",
    "result":"heavy-armor",
    "ingredients":[["copper-plate",100],["steel-plate",50]],
    "type":"recipe",
    "energy_required":8
  },
  "solar-panel":{
    "enabled":false,
    "name":"solar-panel",
    "result":"solar-panel",
    "ingredients":[["steel-plate",5],["electronic-circuit",15],["copper-plate",5]],
    "type":"recipe",
    "energy_required":10
  },
  "personal-roboport-equipment":{
    "enabled":false,
    "name":"personal-roboport-equipment",
    "result":"personal-roboport-equipment",
    "ingredients":[["processing-unit",10],["iron-gear-wheel",40],["steel-plate",20],["battery",45]],
    "type":"recipe",
    "energy_required":10
  },
  "electronic-circuit":{
    "name":"electronic-circuit",
    "result":"electronic-circuit",
    "ingredients":[["iron-plate",1],["copper-cable",3]],
    "type":"recipe",
    "requester_paste_multiplier":10
  },
  "battery-equipment":{
    "enabled":false,
    "name":"battery-equipment",
    "result":"battery-equipment",
    "ingredients":[["battery",5],["steel-plate",10]],
    "type":"recipe",
    "energy_required":10
  },
  "logistic-chest-storage":{
    "enabled":false,
    "name":"logistic-chest-storage",
    "result":"logistic-chest-storage",
    "ingredients":[["steel-chest",1],["electronic-circuit",3],["advanced-circuit",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "pumpjack":{
    "enabled":false,
    "name":"pumpjack",
    "result":"pumpjack",
    "ingredients":[["steel-plate",15],["iron-gear-wheel",10],["electronic-circuit",10],["pipe",10]],
    "type":"recipe",
    "energy_required":20
  },
  "pistol":{
    "name":"pistol",
    "result":"pistol",
    "ingredients":[["copper-plate",5],["iron-plate",5]],
    "type":"recipe",
    "energy_required":1
  },
  "stone-brick":{
    "enabled":true,
    "name":"stone-brick",
    "result":"stone-brick",
    "category":"smelting",
    "type":"recipe",
    "ingredients":[["stone",2]],
    "energy_required":3.5
  },
  "storage-tank":{
    "enabled":false,
    "name":"storage-tank",
    "result":"storage-tank",
    "ingredients":[["iron-plate",20],["steel-plate",5]],
    "type":"recipe",
    "energy_required":3
  },
  "wooden-chest":{
    "name":"wooden-chest",
    "result":"wooden-chest",
    "ingredients":[["wood",4]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "effectivity-module-3":{
    "enabled":false,
    "name":"effectivity-module-3",
    "result":"effectivity-module-3",
    "ingredients":[["effectivity-module-2",5],["advanced-circuit",5],["processing-unit",5],["alien-artifact",1]],
    "type":"recipe",
    "energy_required":60
  },
  "accumulator":{
    "enabled":false,
    "name":"accumulator",
    "result":"accumulator",
    "ingredients":[["iron-plate",2],["battery",5]],
    "type":"recipe",
    "energy_required":10
  },
  "cannon-shell":{
    "enabled":false,
    "name":"cannon-shell",
    "result":"cannon-shell",
    "ingredients":[["steel-plate",4],["plastic-bar",2],["explosives",1]],
    "type":"recipe",
    "energy_required":8
  },
  "green-wire":{
    "enabled":false,
    "name":"green-wire",
    "result":"green-wire",
    "ingredients":[["electronic-circuit",1],["copper-cable",1]],
    "type":"recipe",
    "requester_paste_multiplier":10
  },
  "flamethrower-turret":{
    "enabled":false,
    "name":"flamethrower-turret",
    "result":"flamethrower-turret",
    "ingredients":[["steel-plate",30],["iron-gear-wheel",15],["pipe",10],["engine-unit",5]],
    "type":"recipe",
    "energy_required":20
  },
  "offshore-pump":{
    "name":"offshore-pump",
    "type":"recipe",
    "result":"offshore-pump",
    "ingredients":[["electronic-circuit",2],["pipe",1],["iron-gear-wheel",1]]
  },
  "stone-furnace":{
    "name":"stone-furnace",
    "result":"stone-furnace",
    "ingredients":[["stone",5]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "battery":{
    "enabled":false,
    "name":"battery",
    "result":"battery",
    "category":"chemistry",
    "type":"recipe",
    "ingredients":[{
        "type":"fluid",
        "name":"sulfuric-acid",
        "amount":2
      },["iron-plate",1],["copper-plate",1]],
    "energy_required":5
  },
  "modular-armor":{
    "enabled":false,
    "name":"modular-armor",
    "result":"modular-armor",
    "ingredients":[["advanced-circuit",30],["processing-unit",5],["steel-plate",50]],
    "type":"recipe",
    "energy_required":15
  },
  "railgun":{
    "enabled":false,
    "name":"railgun",
    "result":"railgun",
    "ingredients":[["steel-plate",15],["copper-plate",15],["electronic-circuit",10],["advanced-circuit",5]],
    "type":"recipe",
    "energy_required":8
  },
  "burner-inserter":{
    "name":"burner-inserter",
    "result":"burner-inserter",
    "ingredients":[["iron-plate",1],["iron-gear-wheel",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "fusion-reactor-equipment":{
    "enabled":false,
    "name":"fusion-reactor-equipment",
    "result":"fusion-reactor-equipment",
    "ingredients":[["processing-unit",100],["alien-artifact",30]],
    "type":"recipe",
    "energy_required":10
  },
  "firearm-magazine":{
    "name":"firearm-magazine",
    "result":"firearm-magazine",
    "ingredients":[["iron-plate",2]],
    "type":"recipe",
    "result_count":1,
    "energy_required":2
  },
  "productivity-module":{
    "enabled":false,
    "name":"productivity-module",
    "result":"productivity-module",
    "ingredients":[["advanced-circuit",5],["electronic-circuit",5]],
    "type":"recipe",
    "energy_required":15
  },
  "electric-mining-drill":{
    "name":"electric-mining-drill",
    "result":"electric-mining-drill",
    "ingredients":[["electronic-circuit",3],["iron-gear-wheel",5],["iron-plate",10]],
    "type":"recipe",
    "energy_required":2
  },
  "land-mine":{
    "enabled":false,
    "name":"land-mine",
    "result":"land-mine",
    "ingredients":[["steel-plate",1],["explosives",2]],
    "type":"recipe",
    "result_count":4,
    "energy_required":5
  },
  "electric-energy-interface":{
    "enabled":false,
    "name":"electric-energy-interface",
    "result":"electric-energy-interface",
    "ingredients":[["iron-plate",2],["electronic-circuit",5]],
    "type":"recipe",
    "energy_required":0.5
  },
  "speed-module":{
    "enabled":false,
    "name":"speed-module",
    "result":"speed-module",
    "ingredients":[["advanced-circuit",5],["electronic-circuit",5]],
    "type":"recipe",
    "energy_required":15
  },
  "wood":{
    "name":"wood",
    "result":"wood",
    "ingredients":[["raw-wood",1]],
    "type":"recipe",
    "requester_paste_multiplier":10,
    "result_count":2
  },
  "landfill":{
    "enabled":false,
    "name":"landfill",
    "result":"landfill",
    "category":"crafting",
    "result_count":1,
    "type":"recipe",
    "ingredients":[["stone",20]],
    "energy_required":0.5
  },
  "hazard-concrete":{
    "enabled":false,
    "name":"hazard-concrete",
    "result":"hazard-concrete",
    "category":"crafting",
    "result_count":10,
    "type":"recipe",
    "ingredients":[["concrete",10]],
    "energy_required":0.25
  },
  "concrete":{
    "enabled":false,
    "name":"concrete",
    "result":"concrete",
    "category":"crafting-with-fluid",
    "result_count":10,
    "type":"recipe",
    "ingredients":[["stone-brick",5],["iron-ore",1],{
        "type":"fluid",
        "name":"water",
        "amount":10
      }],
    "energy_required":10
  },
  "satellite":{
    "enabled":false,
    "name":"satellite",
    "result":"satellite",
    "category":"crafting",
    "type":"recipe",
    "ingredients":[["low-density-structure",100],["solar-panel",100],["accumulator",100],["radar",5],["processing-unit",100],["rocket-fuel",50]],
    "energy_required":3
  },
  "steel-chest":{
    "enabled":false,
    "name":"steel-chest",
    "result":"steel-chest",
    "ingredients":[["steel-plate",8]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "energy-shield-mk2-equipment":{
    "enabled":false,
    "name":"energy-shield-mk2-equipment",
    "result":"energy-shield-mk2-equipment",
    "ingredients":[["energy-shield-equipment",10],["processing-unit",10]],
    "type":"recipe",
    "energy_required":10
  },
  "stack-inserter":{
    "enabled":false,
    "name":"stack-inserter",
    "result":"stack-inserter",
    "ingredients":[["iron-gear-wheel",15],["electronic-circuit",15],["advanced-circuit",1],["fast-inserter",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "chemical-plant":{
    "enabled":false,
    "name":"chemical-plant",
    "result":"chemical-plant",
    "ingredients":[["steel-plate",5],["iron-gear-wheel",5],["electronic-circuit",5],["pipe",5]],
    "type":"recipe",
    "energy_required":10
  },
  "fast-underground-belt":{
    "enabled":false,
    "name":"fast-underground-belt",
    "result_count":2,
    "ingredients":[["iron-gear-wheel",20],["underground-belt",2]],
    "type":"recipe",
    "requester_paste_multiplier":4,
    "result":"fast-underground-belt"
  },
  "low-density-structure":{
    "enabled":false,
    "name":"low-density-structure",
    "result":"low-density-structure",
    "category":"crafting",
    "type":"recipe",
    "ingredients":[["steel-plate",10],["copper-plate",5],["plastic-bar",5]],
    "energy_required":30
  },
  "power-switch":{
    "enabled":"false",
    "name":"power-switch",
    "result":"power-switch",
    "ingredients":[["iron-plate",5],["copper-cable",5],["electronic-circuit",2]],
    "type":"recipe",
    "energy_required":2
  },
  "fill-crude-oil-barrel":{
    "name":"fill-crude-oil-barrel",
    "ingredients":[{
        "type":"fluid",
        "name":"crude-oil",
        "amount":25
      },{
        "type":"item",
        "name":"empty-barrel",
        "amount":1
      }],
    "subgroup":"barrel",
    "type":"recipe",
    "energy_required":1,
    "enabled":false,
    "results":[{
        "type":"item",
        "name":"crude-oil-barrel",
        "amount":1
      }],
    "category":"crafting-with-fluid",
    "icon":"__base__/graphics/icons/fluid/fill-crude-oil-barrel.png",
    "order":"b[fill-crude-oil-barrel]"
  },
  "inserter":{
    "name":"inserter",
    "result":"inserter",
    "ingredients":[["electronic-circuit",1],["iron-gear-wheel",1],["iron-plate",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "advanced-oil-processing":{
    "name":"advanced-oil-processing",
    "ingredients":[{
        "type":"fluid",
        "name":"water",
        "amount":5
      },{
        "type":"fluid",
        "name":"crude-oil",
        "amount":10
      }],
    "subgroup":"fluid-recipes",
    "type":"recipe",
    "energy_required":5,
    "enabled":false,
    "results":[{
        "type":"fluid",
        "name":"heavy-oil",
        "amount":1
      },{
        "type":"fluid",
        "name":"light-oil",
        "amount":4.5
      },{
        "type":"fluid",
        "name":"petroleum-gas",
        "amount":5.5
      }],
    "category":"oil-processing",
    "icon":"__base__/graphics/icons/fluid/advanced-oil-processing.png",
    "order":"a[oil-processing]-b[advanced-oil-processing]"
  },
  "explosive-rocket":{
    "enabled":false,
    "name":"explosive-rocket",
    "result":"explosive-rocket",
    "ingredients":[["rocket",1],["explosives",5]],
    "type":"recipe",
    "energy_required":8
  },
  "flame-thrower-ammo":{
    "enabled":false,
    "name":"flame-thrower-ammo",
    "result":"flame-thrower-ammo",
    "category":"chemistry",
    "type":"recipe",
    "ingredients":[{
        "type":"item",
        "name":"iron-plate",
        "amount":5
      },{
        "type":"fluid",
        "name":"light-oil",
        "amount":2.5
      },{
        "type":"fluid",
        "name":"heavy-oil",
        "amount":2.5
      }],
    "energy_required":3
  },
  "cargo-wagon":{
    "enabled":false,
    "name":"cargo-wagon",
    "result":"cargo-wagon",
    "ingredients":[["iron-gear-wheel",10],["iron-plate",20],["steel-plate",20]],
    "type":"recipe"
  },
  "light-armor":{
    "enabled":false,
    "name":"light-armor",
    "result":"light-armor",
    "ingredients":[["iron-plate",40]],
    "type":"recipe",
    "energy_required":3
  },
  "plastic-bar":{
    "enabled":false,
    "name":"plastic-bar",
    "results":[{
        "type":"item",
        "name":"plastic-bar",
        "amount":2
      }],
    "category":"chemistry",
    "ingredients":[{
        "type":"fluid",
        "name":"petroleum-gas",
        "amount":3
      },{
        "type":"item",
        "name":"coal",
        "amount":1
      }],
    "type":"recipe",
    "requester_paste_multiplier":4,
    "energy_required":1
  },
  "rocket-part":{
    "enabled":false,
    "name":"rocket-part",
    "result":"rocket-part",
    "category":"rocket-building",
    "ingredients":[["low-density-structure",10],["rocket-fuel",10],["rocket-control-unit",10]],
    "type":"recipe",
    "hidden":true,
    "energy_required":3
  },
  "electric-furnace":{
    "enabled":false,
    "name":"electric-furnace",
    "result":"electric-furnace",
    "ingredients":[["steel-plate",15],["advanced-circuit",5],["stone-brick",10]],
    "type":"recipe",
    "energy_required":5
  },
  "steel-plate":{
    "enabled":false,
    "name":"steel-plate",
    "result":"steel-plate",
    "category":"smelting",
    "type":"recipe",
    "ingredients":[["iron-plate",5]],
    "energy_required":17.5
  },
  "light-oil-cracking":{
    "name":"light-oil-cracking",
    "ingredients":[{
        "type":"fluid",
        "name":"water",
        "amount":3
      },{
        "type":"fluid",
        "name":"light-oil",
        "amount":3
      }],
    "subgroup":"fluid-recipes",
    "type":"recipe",
    "energy_required":5,
    "enabled":false,
    "results":[{
        "type":"fluid",
        "name":"petroleum-gas",
        "amount":2
      }],
    "category":"chemistry",
    "main_product":"",
    "icon":"__base__/graphics/icons/fluid/light-oil-cracking.png",
    "order":"b[fluid-chemistry]-b[light-oil-cracking]"
  },
  "assembling-machine-2":{
    "enabled":false,
    "name":"assembling-machine-2",
    "result":"assembling-machine-2",
    "ingredients":[["iron-plate",9],["electronic-circuit",3],["iron-gear-wheel",5],["assembling-machine-1",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "decider-combinator":{
    "enabled":"false",
    "name":"decider-combinator",
    "result":"decider-combinator",
    "ingredients":[["copper-cable",5],["electronic-circuit",5]],
    "type":"recipe"
  },
  "fast-inserter":{
    "enabled":false,
    "name":"fast-inserter",
    "result":"fast-inserter",
    "ingredients":[["electronic-circuit",2],["iron-plate",2],["inserter",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "small-plane":{
    "enabled":false,
    "name":"small-plane",
    "result":"small-plane",
    "category":"crafting",
    "type":"recipe",
    "ingredients":[["plastic-bar",100],["advanced-circuit",200],["electric-engine-unit",20],["battery",100]],
    "energy_required":30
  },
  "combat-shotgun":{
    "enabled":false,
    "name":"combat-shotgun",
    "result":"combat-shotgun",
    "ingredients":[["steel-plate",15],["iron-gear-wheel",5],["copper-plate",10],["wood",10]],
    "type":"recipe",
    "energy_required":8
  },
  "rocket-fuel":{
    "enabled":false,
    "name":"rocket-fuel",
    "result":"rocket-fuel",
    "category":"crafting",
    "type":"recipe",
    "ingredients":[["solid-fuel",10]],
    "energy_required":30
  },
  "small-pump":{
    "enabled":false,
    "name":"small-pump",
    "result":"small-pump",
    "ingredients":[["electric-engine-unit",1],["steel-plate",1],["pipe",1]],
    "type":"recipe",
    "energy_required":2
  },
  "laser-turret":{
    "enabled":false,
    "name":"laser-turret",
    "result":"laser-turret",
    "ingredients":[["steel-plate",20],["electronic-circuit",20],["battery",12]],
    "type":"recipe",
    "energy_required":20
  },
  "tank":{
    "enabled":false,
    "name":"tank",
    "result":"tank",
    "ingredients":[["engine-unit",16],["steel-plate",50],["iron-gear-wheel",15],["advanced-circuit",5]],
    "type":"recipe"
  },
  "sulfur":{
    "enabled":false,
    "name":"sulfur",
    "results":[{
        "type":"item",
        "name":"sulfur",
        "amount":2
      }],
    "category":"chemistry",
    "type":"recipe",
    "ingredients":[{
        "type":"fluid",
        "name":"water",
        "amount":3
      },{
        "type":"fluid",
        "name":"petroleum-gas",
        "amount":3
      }],
    "energy_required":1
  },
  "explosives":{
    "enabled":false,
    "name":"explosives",
    "result":"explosives",
    "category":"chemistry",
    "type":"recipe",
    "ingredients":[{
        "type":"item",
        "name":"sulfur",
        "amount":1
      },{
        "type":"item",
        "name":"coal",
        "amount":1
      },{
        "type":"fluid",
        "name":"water",
        "amount":1
      }],
    "energy_required":5
  },
  "transport-belt":{
    "name":"transport-belt",
    "result":"transport-belt",
    "ingredients":[["iron-plate",1],["iron-gear-wheel",1]],
    "type":"recipe",
    "requester_paste_multiplier":4,
    "result_count":2
  },
  "alien-science-pack":{
    "enabled":false,
    "name":"alien-science-pack",
    "result":"alien-science-pack",
    "ingredients":[["alien-artifact",1]],
    "type":"recipe",
    "result_count":10,
    "energy_required":12
  },
  "express-loader":{
    "enabled":false,
    "name":"express-loader",
    "result":"express-loader",
    "ingredients":[["express-transport-belt",5],["fast-loader",1]],
    "type":"recipe",
    "energy_required":10
  },
  "personal-laser-defense-equipment":{
    "enabled":false,
    "name":"personal-laser-defense-equipment",
    "result":"personal-laser-defense-equipment",
    "ingredients":[["processing-unit",1],["steel-plate",5],["laser-turret",5]],
    "type":"recipe",
    "energy_required":10
  },
  "iron-stick":{
    "name":"iron-stick",
    "result":"iron-stick",
    "ingredients":[["iron-plate",1]],
    "type":"recipe",
    "requester_paste_multiplier":10,
    "result_count":2
  },
  "electric-engine-unit":{
    "enabled":false,
    "name":"electric-engine-unit",
    "result":"electric-engine-unit",
    "category":"crafting-with-fluid",
    "type":"recipe",
    "ingredients":[["engine-unit",1],{
        "type":"fluid",
        "name":"lubricant",
        "amount":2
      },["electronic-circuit",2]],
    "energy_required":20
  },
  "medium-electric-pole":{
    "enabled":false,
    "name":"medium-electric-pole",
    "result":"medium-electric-pole",
    "ingredients":[["steel-plate",2],["copper-plate",2]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "oil-refinery":{
    "enabled":false,
    "name":"oil-refinery",
    "result":"oil-refinery",
    "ingredients":[["steel-plate",15],["iron-gear-wheel",10],["stone-brick",10],["electronic-circuit",10],["pipe",10]],
    "type":"recipe",
    "energy_required":20
  },
  "deconstruction-planner":{
    "enabled":false,
    "name":"deconstruction-planner",
    "result":"deconstruction-planner",
    "ingredients":[["advanced-circuit",1]],
    "type":"recipe",
    "energy_required":1
  },
  "blueprint-book":{
    "enabled":false,
    "name":"blueprint-book",
    "result":"blueprint-book",
    "ingredients":[["advanced-circuit",15]],
    "type":"recipe",
    "energy_required":5
  },
  "effectivity-module-2":{
    "enabled":false,
    "name":"effectivity-module-2",
    "result":"effectivity-module-2",
    "ingredients":[["effectivity-module",4],["advanced-circuit",5],["processing-unit",5]],
    "type":"recipe",
    "energy_required":30
  },
  "blueprint":{
    "enabled":false,
    "name":"blueprint",
    "result":"blueprint",
    "ingredients":[["advanced-circuit",1]],
    "type":"recipe",
    "energy_required":1
  },
  "roboport":{
    "enabled":false,
    "name":"roboport",
    "result":"roboport",
    "ingredients":[["steel-plate",45],["iron-gear-wheel",45],["advanced-circuit",45]],
    "type":"recipe",
    "energy_required":15
  },
  "stack-filter-inserter":{
    "enabled":false,
    "name":"stack-filter-inserter",
    "result":"stack-filter-inserter",
    "ingredients":[["stack-inserter",1],["electronic-circuit",5]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "shotgun-shell":{
    "enabled":false,
    "name":"shotgun-shell",
    "result":"shotgun-shell",
    "ingredients":[["copper-plate",2],["iron-plate",2]],
    "type":"recipe",
    "energy_required":3
  },
  "big-electric-pole":{
    "enabled":false,
    "name":"big-electric-pole",
    "result":"big-electric-pole",
    "ingredients":[["steel-plate",5],["copper-plate",5]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "substation":{
    "enabled":false,
    "name":"substation",
    "result":"substation",
    "ingredients":[["steel-plate",10],["advanced-circuit",5],["copper-plate",5]],
    "type":"recipe"
  },
  "sulfuric-acid":{
    "enabled":false,
    "name":"sulfuric-acid",
    "results":[{
        "type":"fluid",
        "name":"sulfuric-acid",
        "amount":5
      }],
    "category":"chemistry",
    "subgroup":"fluid-recipes",
    "type":"recipe",
    "ingredients":[{
        "type":"item",
        "name":"sulfur",
        "amount":5
      },{
        "type":"item",
        "name":"iron-plate",
        "amount":1
      },{
        "type":"fluid",
        "name":"water",
        "amount":10
      }],
    "energy_required":1
  },
  "speed-module-2":{
    "enabled":false,
    "name":"speed-module-2",
    "result":"speed-module-2",
    "ingredients":[["speed-module",4],["processing-unit",5],["advanced-circuit",5]],
    "type":"recipe",
    "energy_required":30
  },
  "destroyer-capsule":{
    "enabled":false,
    "name":"destroyer-capsule",
    "result":"destroyer-capsule",
    "ingredients":[["distractor-capsule",4],["speed-module",1]],
    "type":"recipe",
    "energy_required":15
  },
  "submachine-gun":{
    "enabled":false,
    "name":"submachine-gun",
    "result":"submachine-gun",
    "ingredients":[["iron-gear-wheel",10],["copper-plate",5],["iron-plate",10]],
    "type":"recipe",
    "energy_required":3
  },
  "lab":{
    "name":"lab",
    "result":"lab",
    "ingredients":[["electronic-circuit",10],["iron-gear-wheel",10],["transport-belt",4]],
    "type":"recipe",
    "energy_required":5
  },
  "rocket-silo":{
    "enabled":false,
    "name":"rocket-silo",
    "result":"rocket-silo",
    "ingredients":[["steel-plate",1000],["concrete",1000],["pipe",100],["processing-unit",200],["electric-engine-unit",200]],
    "type":"recipe",
    "requester_paste_multiplier":1,
    "energy_required":30
  },
  "logistic-chest-requester":{
    "enabled":false,
    "name":"logistic-chest-requester",
    "result":"logistic-chest-requester",
    "ingredients":[["steel-chest",1],["electronic-circuit",3],["advanced-circuit",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "repair-pack":{
    "name":"repair-pack",
    "result":"repair-pack",
    "ingredients":[["electronic-circuit",1],["iron-gear-wheel",1]],
    "type":"recipe",
    "requester_paste_multiplier":10
  },
  "red-wire":{
    "enabled":false,
    "name":"red-wire",
    "result":"red-wire",
    "ingredients":[["electronic-circuit",1],["copper-cable",1]],
    "type":"recipe",
    "requester_paste_multiplier":10
  },
  "logistic-chest-passive-provider":{
    "enabled":false,
    "name":"logistic-chest-passive-provider",
    "result":"logistic-chest-passive-provider",
    "ingredients":[["steel-chest",1],["electronic-circuit",3],["advanced-circuit",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "construction-robot":{
    "enabled":false,
    "name":"construction-robot",
    "result":"construction-robot",
    "ingredients":[["flying-robot-frame",1],["electronic-circuit",2]],
    "type":"recipe"
  },
  "defender-capsule":{
    "enabled":false,
    "name":"defender-capsule",
    "result":"defender-capsule",
    "ingredients":[["piercing-rounds-magazine",1],["electronic-circuit",2],["iron-gear-wheel",3]],
    "type":"recipe",
    "energy_required":8
  },
  "logistic-robot":{
    "enabled":false,
    "name":"logistic-robot",
    "result":"logistic-robot",
    "ingredients":[["flying-robot-frame",1],["advanced-circuit",2]],
    "type":"recipe"
  },
  "advanced-circuit":{
    "enabled":false,
    "name":"advanced-circuit",
    "result":"advanced-circuit",
    "ingredients":[["electronic-circuit",2],["plastic-bar",2],["copper-cable",4]],
    "type":"recipe",
    "requester_paste_multiplier":5,
    "energy_required":8
  },
  "diesel-locomotive":{
    "enabled":false,
    "name":"diesel-locomotive",
    "result":"diesel-locomotive",
    "ingredients":[["engine-unit",20],["electronic-circuit",10],["steel-plate",30]],
    "type":"recipe"
  },
  "shotgun":{
    "enabled":false,
    "name":"shotgun",
    "result":"shotgun",
    "ingredients":[["iron-plate",15],["iron-gear-wheel",5],["copper-plate",10],["wood",5]],
    "type":"recipe",
    "energy_required":4
  },
  "flying-robot-frame":{
    "enabled":false,
    "name":"flying-robot-frame",
    "result":"flying-robot-frame",
    "ingredients":[["electric-engine-unit",1],["battery",2],["steel-plate",1],["electronic-circuit",3]],
    "type":"recipe",
    "energy_required":20
  },
  "boiler":{
    "name":"boiler",
    "type":"recipe",
    "result":"boiler",
    "ingredients":[["stone-furnace",1],["pipe",1]]
  },
  "assembling-machine-1":{
    "enabled":false,
    "name":"assembling-machine-1",
    "result":"assembling-machine-1",
    "ingredients":[["electronic-circuit",3],["iron-gear-wheel",5],["iron-plate",9]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "iron-gear-wheel":{
    "name":"iron-gear-wheel",
    "result":"iron-gear-wheel",
    "ingredients":[["iron-plate",2]],
    "type":"recipe",
    "requester_paste_multiplier":10
  },
  "discharge-defense-remote":{
    "enabled":false,
    "name":"discharge-defense-remote",
    "result":"discharge-defense-remote",
    "ingredients":[["electronic-circuit",1]],
    "type":"recipe"
  },
  "constant-combinator":{
    "enabled":"false",
    "name":"constant-combinator",
    "result":"constant-combinator",
    "ingredients":[["copper-cable",5],["electronic-circuit",2]],
    "type":"recipe"
  },
  "fast-loader":{
    "enabled":false,
    "name":"fast-loader",
    "result":"fast-loader",
    "ingredients":[["fast-transport-belt",5],["loader",1]],
    "type":"recipe",
    "energy_required":3
  },
  "loader":{
    "enabled":false,
    "name":"loader",
    "result":"loader",
    "ingredients":[["inserter",5],["electronic-circuit",5],["iron-gear-wheel",5],["iron-plate",5],["transport-belt",5]],
    "type":"recipe",
    "energy_required":1
  },
  "express-underground-belt":{
    "enabled":false,
    "name":"express-underground-belt",
    "result_count":2,
    "category":"crafting-with-fluid",
    "type":"recipe",
    "result":"express-underground-belt",
    "ingredients":[["iron-gear-wheel",40],["fast-underground-belt",2],{
        "type":"fluid",
        "name":"lubricant",
        "amount":4
      }]
  },
  "logistic-chest-active-provider":{
    "enabled":false,
    "name":"logistic-chest-active-provider",
    "result":"logistic-chest-active-provider",
    "ingredients":[["steel-chest",1],["electronic-circuit",3],["advanced-circuit",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "assembling-machine-3":{
    "enabled":false,
    "name":"assembling-machine-3",
    "result":"assembling-machine-3",
    "ingredients":[["speed-module",4],["assembling-machine-2",2]],
    "type":"recipe"
  },
  "rocket-control-unit":{
    "enabled":false,
    "name":"rocket-control-unit",
    "result":"rocket-control-unit",
    "category":"crafting",
    "type":"recipe",
    "ingredients":[["processing-unit",1],["speed-module",1]],
    "energy_required":30
  },
  "productivity-module-3":{
    "enabled":false,
    "name":"productivity-module-3",
    "result":"productivity-module-3",
    "ingredients":[["productivity-module-2",5],["advanced-circuit",5],["processing-unit",5],["alien-artifact",1]],
    "type":"recipe",
    "energy_required":60
  },
  "effectivity-module":{
    "enabled":false,
    "name":"effectivity-module",
    "result":"effectivity-module",
    "ingredients":[["advanced-circuit",5],["electronic-circuit",5]],
    "type":"recipe",
    "energy_required":15
  },
  "splitter":{
    "enabled":false,
    "name":"splitter",
    "result":"splitter",
    "ingredients":[["electronic-circuit",5],["iron-plate",5],["transport-belt",4]],
    "type":"recipe",
    "requester_paste_multiplier":4,
    "energy_required":1
  },
  "science-pack-1":{
    "name":"science-pack-1",
    "result":"science-pack-1",
    "ingredients":[["copper-plate",1],["iron-gear-wheel",1]],
    "type":"recipe",
    "energy_required":5
  },
  "small-electric-pole":{
    "name":"small-electric-pole",
    "result":"small-electric-pole",
    "ingredients":[["wood",2],["copper-cable",2]],
    "type":"recipe",
    "requester_paste_multiplier":4,
    "result_count":2
  },
  "lubricant":{
    "enabled":false,
    "name":"lubricant",
    "results":[{
        "type":"fluid",
        "name":"lubricant",
        "amount":1
      }],
    "category":"chemistry",
    "subgroup":"fluid-recipes",
    "type":"recipe",
    "ingredients":[{
        "type":"fluid",
        "name":"heavy-oil",
        "amount":1
      }],
    "energy_required":1
  },
  "science-pack-2":{
    "name":"science-pack-2",
    "result":"science-pack-2",
    "ingredients":[["inserter",1],["transport-belt",1]],
    "type":"recipe",
    "energy_required":6
  },
  "long-handed-inserter":{
    "enabled":false,
    "name":"long-handed-inserter",
    "result":"long-handed-inserter",
    "ingredients":[["iron-gear-wheel",1],["iron-plate",1],["inserter",1]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "energy-shield-equipment":{
    "enabled":false,
    "name":"energy-shield-equipment",
    "result":"energy-shield-equipment",
    "ingredients":[["advanced-circuit",5],["steel-plate",10]],
    "type":"recipe",
    "energy_required":10
  },
  "solid-fuel-from-heavy-oil":{
    "name":"solid-fuel-from-heavy-oil",
    "ingredients":[{
        "type":"fluid",
        "name":"heavy-oil",
        "amount":2
      }],
    "subgroup":"fluid-recipes",
    "type":"recipe",
    "energy_required":3,
    "enabled":false,
    "results":[{
        "type":"item",
        "name":"solid-fuel",
        "amount":1
      }],
    "category":"chemistry",
    "icon":"__base__/graphics/icons/solid-fuel-from-heavy-oil.png",
    "order":"b[fluid-chemistry]-e[solid-fuel-from-heavy-oil]"
  },
  "small-lamp":{
    "enabled":false,
    "name":"small-lamp",
    "result":"small-lamp",
    "ingredients":[["electronic-circuit",1],["iron-stick",3],["iron-plate",1]],
    "type":"recipe"
  },
  "solid-fuel-from-petroleum-gas":{
    "name":"solid-fuel-from-petroleum-gas",
    "ingredients":[{
        "type":"fluid",
        "name":"petroleum-gas",
        "amount":2
      }],
    "subgroup":"fluid-recipes",
    "type":"recipe",
    "energy_required":3,
    "enabled":false,
    "results":[{
        "type":"item",
        "name":"solid-fuel",
        "amount":1
      }],
    "category":"chemistry",
    "icon":"__base__/graphics/icons/solid-fuel-from-petroleum-gas.png",
    "order":"b[fluid-chemistry]-d[solid-fuel-from-petroleum-gas]"
  },
  "empty-crude-oil-barrel":{
    "name":"empty-crude-oil-barrel",
    "ingredients":[{
        "type":"item",
        "name":"crude-oil-barrel",
        "amount":1
      }],
    "subgroup":"barrel",
    "type":"recipe",
    "energy_required":1,
    "enabled":false,
    "results":[{
        "type":"fluid",
        "name":"crude-oil",
        "amount":25
      },{
        "type":"item",
        "name":"empty-barrel",
        "amount":1
      }],
    "category":"crafting-with-fluid",
    "icon":"__base__/graphics/icons/fluid/empty-crude-oil-barrel.png",
    "order":"c[empty-crude-oil-barrel]"
  },
  "arithmetic-combinator":{
    "enabled":"false",
    "name":"arithmetic-combinator",
    "result":"arithmetic-combinator",
    "ingredients":[["copper-cable",5],["electronic-circuit",5]],
    "type":"recipe"
  },
  "rocket":{
    "enabled":false,
    "name":"rocket",
    "result":"rocket",
    "ingredients":[["electronic-circuit",1],["explosives",2],["iron-plate",2]],
    "type":"recipe",
    "energy_required":8
  },
  "piercing-rounds-magazine":{
    "enabled":false,
    "name":"piercing-rounds-magazine",
    "result":"piercing-rounds-magazine",
    "ingredients":[["copper-plate",5],["steel-plate",1]],
    "type":"recipe",
    "energy_required":3
  },
  "stone-wall":{
    "enabled":false,
    "name":"stone-wall",
    "result":"stone-wall",
    "ingredients":[["stone-brick",5]],
    "type":"recipe",
    "requester_paste_multiplier":10
  },
  "iron-plate":{
    "name":"iron-plate",
    "result":"iron-plate",
    "category":"smelting",
    "type":"recipe",
    "ingredients":[["iron-ore",1]],
    "energy_required":3.5
  },
  "poison-capsule":{
    "enabled":false,
    "name":"poison-capsule",
    "result":"poison-capsule",
    "ingredients":[["steel-plate",3],["electronic-circuit",3],["coal",10]],
    "type":"recipe",
    "energy_required":8
  },
  "solid-fuel-from-light-oil":{
    "name":"solid-fuel-from-light-oil",
    "ingredients":[{
        "type":"fluid",
        "name":"light-oil",
        "amount":1
      }],
    "subgroup":"fluid-recipes",
    "type":"recipe",
    "energy_required":3,
    "enabled":false,
    "results":[{
        "type":"item",
        "name":"solid-fuel",
        "amount":1
      }],
    "category":"chemistry",
    "icon":"__base__/graphics/icons/solid-fuel-from-light-oil.png",
    "order":"b[fluid-chemistry]-c[solid-fuel-from-light-oil]"
  },
  "speed-module-3":{
    "enabled":false,
    "name":"speed-module-3",
    "result":"speed-module-3",
    "ingredients":[["speed-module-2",4],["advanced-circuit",5],["processing-unit",5],["alien-artifact",1]],
    "type":"recipe",
    "energy_required":60
  },
  "exoskeleton-equipment":{
    "enabled":false,
    "name":"exoskeleton-equipment",
    "result":"exoskeleton-equipment",
    "ingredients":[["processing-unit",10],["electric-engine-unit",30],["steel-plate",20]],
    "type":"recipe",
    "energy_required":10
  },
  "power-armor":{
    "enabled":false,
    "name":"power-armor",
    "result":"power-armor",
    "ingredients":[["processing-unit",40],["electric-engine-unit",20],["steel-plate",40],["alien-artifact",10]],
    "type":"recipe",
    "requester_paste_multiplier":1,
    "energy_required":20
  },
  "train-stop":{
    "enabled":false,
    "name":"train-stop",
    "result":"train-stop",
    "ingredients":[["electronic-circuit",5],["iron-plate",10],["steel-plate",3]],
    "type":"recipe"
  },
  "car":{
    "enabled":false,
    "name":"car",
    "result":"car",
    "ingredients":[["engine-unit",8],["iron-plate",20],["steel-plate",5]],
    "type":"recipe"
  },
  "basic-oil-processing":{
    "name":"basic-oil-processing",
    "ingredients":[{
        "type":"fluid",
        "name":"crude-oil",
        "amount":10
      }],
    "subgroup":"fluid-recipes",
    "type":"recipe",
    "energy_required":5,
    "enabled":false,
    "results":[{
        "type":"fluid",
        "name":"heavy-oil",
        "amount":3
      },{
        "type":"fluid",
        "name":"light-oil",
        "amount":3
      },{
        "type":"fluid",
        "name":"petroleum-gas",
        "amount":4
      }],
    "category":"oil-processing",
    "icon":"__base__/graphics/icons/fluid/basic-oil-processing.png",
    "order":"a[oil-processing]-a[basic-oil-processing]"
  },
  "radar":{
    "name":"radar",
    "result":"radar",
    "ingredients":[["electronic-circuit",5],["iron-gear-wheel",5],["iron-plate",10]],
    "type":"recipe",
    "requester_paste_multiplier":4
  },
  "express-splitter":{
    "enabled":false,
    "name":"express-splitter",
    "result":"express-splitter",
    "category":"crafting-with-fluid",
    "type":"recipe",
    "ingredients":[["fast-splitter",1],["iron-gear-wheel",10],["advanced-circuit",10],{
        "type":"fluid",
        "name":"lubricant",
        "amount":8
      }],
    "energy_required":2
  },
  "rail":{
    "enabled":false,
    "name":"rail",
    "result":"rail",
    "ingredients":[["stone",1],["iron-stick",1],["steel-plate",1]],
    "type":"recipe",
    "requester_paste_multiplier":4,
    "result_count":2
  },
  "discharge-defense-equipment":{
    "enabled":false,
    "name":"discharge-defense-equipment",
    "result":"discharge-defense-equipment",
    "ingredients":[["processing-unit",5],["steel-plate",20],["laser-turret",10]],
    "type":"recipe",
    "energy_required":10
  }
}
);
